development:
  adapter: postgresql
  encoding: unicode
  database: nbavis_development
  pool: 5
  #username: postgres
  #password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: nbavis_test
  pool: 5
  #username: postgres
  #password:
  min_messages: WARNING
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: nbavis_production
  pool: 5
  # username: postgres
  # password:
  host: localhost